export const ENUM_TRANSACTION_TYPE = {
    CREDIT: 'CREDIT',
    DEBIT: 'DEBIT',
};

export const ENUM_TRANSACTION_REASON = {
    BID_ACCEPT_PAYMENT: 'BID_ACCEPT_PAYMENT',
    REFERRAL_BONUS: 'REFERRAL_BONUS',
};
