/* eslint-disable no-unused-vars */
export enum ENUM_EXTENSION_REQUEST_STATUS {
    PENDING = 'PENDING',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    RESOLVED = 'RESOLVED',
    REJECTED_BY_ADMIN = 'REJECTED_BY_ADMIN',
    APPROVED_BY_ADMIN = 'APPROVED_BY_ADMIN',
}
