/* eslint-disable no-unused-vars */
export enum ENUM_IDENTIFICATION_DOCUMENT {
    NATIONAL_IDENTIFICATION_NUMBER = 'NATIONAL_IDENTIFICATION_NUMBER',
    VOTERS_CARD = 'VOTERS_CARD',
    INTERNATIONAL_PASSPORT = 'INTERNATIONAL_PASSPORT',
    DRIVERS_LICENSE = 'DRIVERS_LICENSE',
}
