/* eslint-disable no-unused-vars */
export enum ENUM_DISPUTE_REQUEST_TYPE {
    TASK_RESCHEDULE_REQUEST = 'TASK_RESCHEDULE_REQUEST',
    TASK_CANCELLATION_REQUEST = 'TASK_CANCELLATION_REQUEST',
}

export enum ENUM_DISPUTE_STATUS {
    PENDING = 'PENDING',
    RESOLVED = 'RESOLVED',
}
